import recoLogo from "../../public/images/logo/logo-2x.png";
import reco from "../../public/images/product.png"
export const products = [
  {
    id: 1,
    name: "RECO",
    photo: reco,
    photoProduct: reco,
    volume: "Об'єм",
    description:
      "Інноваційний реконструктор для відновлення сильно пошкодженого волосся...",
    sizes: {
      "15 ML": 600,
      "30 ML": 1200,
      "50 ML": 1800,
      "100 ML": 3240,
      "200 ML": 6000,
    },
    price: 600,
    badgeInfo: "Хіт продажів",
    isNew: true,
  },
  {
    id: 2,
    name: "HAPPY END",
    photo: recoLogo,
    photoProduct: "/images/product.png",
    volume: "Об'єм",
    description: "Засіб для живлення, зволоження та блиску волосся...",
    sizes: {
      "15 ML": 720,
      "30 ML": 1440,
      "50 ML": 2160,
      "100 ML": 3960,
    },
    price: 720,
    badgeInfo: "Новинка",
    isNew: true,
  },
  {
    id: 3,
    name: "REC ON",
    photo: recoLogo,
    photoProduct: "/images/product.png",
    volume: "Об'єм",
    description: "Спрей-реконструктор з активною формулою для пористого волосся...",
    sizes: {
      "100 ML": 1560,
      "250 ML": 3120,
    },
    price: 1560,
    badgeInfo: "Рекомендовано",
    isNew: false,
  },
  {
    id: 4,
    name: "RecOil",
    photo: recoLogo,
    photoProduct: "/images/product.png",
    volume: "Об'єм",
    description: "Коктейль з натуральних олій для зволоження волосся...",
    sizes: {
      "15 ML": 720,
      "30 ML": 1440,
    },
    price: 720,
    badgeInfo: "Найкращий вибір",
    isNew: false,
  },
  {
    id: 5,
    name: "TERMO CONTROL",
    photo: recoLogo,
    photoProduct: "/images/product.png",
    volume: "Об'єм",
    description: "Спрей-термозахист з формулою RECO...",
    sizes: {
      "100 ML": 1440,
      "250 ML": 2880,
    },
    price: 1440,
    badgeInfo: "Хіт продажів",
    isNew: true,
  },
  {
    id: 6,
    name: "VOL UP CRAZY",
    photo: recoLogo,
    photoProduct: "/images/product.png",
    volume: "Об'єм",
    description: "Спрей для прикореневого об’єму...",
    sizes: {
      "100 ML": 1080,
      "250 ML": 2160,
    },
    price: 1080,
    badgeInfo: "Рекомендовано",
    isNew: false,
  },
  {
    id: 7,
    name: "EVERY DAY",
    photo: recoLogo,
    photoProduct: "/images/product.png",
    volume: "Об'єм",
    description: "Шампунь для щоденного використання...",
    sizes: {
      "50 ML": 600,
      "100 ML": 1140,
      "200 ML": 2160,
    },
    price: 600,
    badgeInfo: "Топ продажів",
    isNew: true,
  },
  {
    id: 8,
    name: "SHAMPOO HIDRATING",
    photo: recoLogo,
    photoProduct: "/images/product.png",
    volume: "Об'єм",
    description: "Зволожуючий шампунь для здорового волосся...",
    sizes: {
      "100 ML": 450,
      "250 ML": 900,
    },
    price: 450,
    badgeInfo: "Новинка",
    isNew: true,
  },
];
